name: Generate module diff
on:
  pull_request:
    branches:
      - main
    paths:
      - 'modules/**'

jobs:
  generate_module_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Check out PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Generate module diff ( ⭐ 🔍 Expand here to see the diff ⭐)
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@12fcc46e174371374aac63d1e48d2364610d6d6d
        with:
          action-type: diff_module
